# Generated by Django 5.2.13 on 2026-06-21 18:23

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_item_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='historicalmusic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalmusic',
            name='item',
        ),
        migrations.RemoveField(
            model_name='historicalmusic',
            name='progressed_at',
        ),
        migrations.RemoveField(
            model_name='historicalmusic',
            name='user',
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmusic',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='music',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AlterField(
            model_name='music',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.DecimalValidator(3, 1), django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='music',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='Completed', max_length=20),
        ),
    ]
