# Generated by Django 5.2.13 on 2026-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_music_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0055_create_default_users'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='user',
                    name='last_search_type_valid',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'boardgame', 'music'])), name='last_search_type_valid'),
        ),
    ]
