# Generated by Django 5.2.13 on 2026-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_drop_external_list_models'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0058_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection_columns',
            field=models.PositiveSmallIntegerField(default=12, help_text='Number of grid columns on collection pages'),
        ),
        migrations.AddField(
            model_name='user',
            name='collection_items_per_page',
            field=models.PositiveSmallIntegerField(default=96, help_text='Number of items per page on collection pages'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('collection_items_per_page__in', [6, 12, 24, 48, 96])), name='collection_items_per_page_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('collection_columns__in', [3, 4, 5, 6, 8, 12, 24])), name='collection_columns_valid'),
        ),
    ]
