# Generated by Django 5.2.13 on 2026-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_collections', '0004_collection_item_exclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionitemexclusion',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Boardgame'), ('music', 'Music')], max_length=10),
        ),
    ]
